websites/models.py
import firebase_admin
from firebase_admin import credentials, db

# import credentials file
cred = credentials.Certificate('websites/serviceAccount.json')
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://pln-ice-default-rtdb.asia-southeast1.firebasedatabase.app'
})

# get data from realtime database
def get_data_dashboard():
  ref = db.reference('/')
  return ref.get()

# update data to realtime database
def update_data(data):
  ref = db.reference('/gudang')
  ref.update(data)

websites/__init__.py
from flask import Flask

app = Flask(__name__)

def create_app():
  app.config['SECRET_KEY'] = 'plniceee'

  from .views import views

  app.register_blueprint(views, url_prefix = '/')
  
  return app

websites/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import get_data_dashboard, update_data

views = Blueprint('views', __name__)

@views.route('/')
def dashboard():  
    return render_template('dashboard.html', data = get_data_dashboard())
  
@views.route('/api')
def api():  
    return "api"

@views.route('/sistem')
def sistem():  
    return render_template('sistem.html')

@views.route('/stok')
def stok():  
    return render_template('stok.html', data=get_data_dashboard())

@views.route('/updateCabai', methods=['POST', 'GET'])
def updateCabai():  
    if request.method == 'POST':
        cabai = request.form['cabai']
        update_data({
            'cabai' : int(cabai)
        })
        return redirect(url_for('views.stok'))

@views.route('/updatePupuk', methods=['POST', 'GET']) 
def updatePupuk():  
    if request.method == 'POST':
        pupuk = request.form['pupuk']
        update_data({
            'pupuk' : int(pupuk)
        })
        return redirect(url_for('views.stok'))
        

@views.route('/updateBibit', methods=['POST', 'GET'])
def updateBibit():  
    if request.method == 'POST':
        bibit = request.form['bibit']
        update_data({
            'bibit' : int(bibit)
        })
        return redirect(url_for('views.stok'))
        

websites/templates/stok.html
{% extends 'template.html' %}

{% block title %} Stok📥 {% endblock %}

{% block body %}
<div class="app-wrapper">

  <div class="app-content pt-3 p-md-3 p-lg-4">

    <h1 class="app-page-title">Overviews </h1>
    <div class="container-xl">
      <div class="container py-1 h-100">
        <!-- block stok -->
        <div class="row g-4 mb-4">

          <div class="blok hidden-right col-sm-4 col-md-4">
            <div class="card  " style="border-radius: 25px;">
              <div class="card-body p-4">
                <div id="demo1" class="carousel slide" data-ride="carousel">
                  <!-- Carousel inner -->
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <div class="d-flex justify-content-between mb-4 pb-2">
                        <div>
                          <h5 class="text-muted mb-0">Cabai</h5>
                          <h2 class="display-2"><strong>{{ data['gudang']['cabai'] }}kg</strong></h2>
                        </div>

                        <div class="fa-lg">
                          <img src="{{ url_for('static', filename = 'images/icons/chili.png') }}" width="100px">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="blok hidden-right col-sm-4 col-md-4">
            <div class="card" style="border-radius: 25px;">
              <div class="card-body p-4">
                <div id="demo1" class="carousel slide" data-ride="carousel">
                  <!-- Carousel inner -->
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <div class="d-flex justify-content-between mb-4 pb-2">
                        <div>
                          <h5 class="text-muted mb-0">Pupuk</h5>
                          <h2 class="display-2"><strong>{{ data['gudang']['pupuk'] }}kg</strong></h2>
                        </div>
                        <div class="fa-lg">
                          <img src="{{ url_for('static', filename = 'images/icons/fertilization.png') }}" width="100px">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="blok hidden-right col-sm-4 col-md-4">
            <div class="card" style="border-radius: 25px;">
              <div class="card-body p-4">
                <div id="demo1" class="carousel slide" data-ride="carousel">
                  <!-- Carousel inner -->
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <div class="d-flex justify-content-between mb-4 pb-2">
                        <div>
                          <h5 class="text-muted mb-0">Bibit</h5>
                          <h2 class="display-2"><strong>{{ data['gudang']['bibit'] }}kg</strong></h2>
                        </div>
                        <div>
                          <img src="{{ url_for('static', filename = 'images/icons/seed.png') }}" width="100px">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

        <div class="hidden-down col-sm-12 col-lg-6">
          <div class="card" style="border-radius: 25px;">
            <div class="row card-body p-4">


              <form action="{{ url_for('views.updateCabai') }}" method="POST">
                <div class="form-outline col-12">
                  <input type="number" name="cabai" id="typeNumber" class="form-control" />
                  <label class="form-label" for="typeNumber">Berapa Kg Cabainya?</label>
                </div>
                <button type="submit" class="btn btn-success col-12 mt-2 mb-4 " style="border-radius: 10px;">Update
                  Cabai🌶️</button>
              </form>

              <form action="{{ url_for('views.updatePupuk') }}" method="POST">
                <div class="form-outline col-12">
                  <input type="number" name="pupuk" id="typeNumber" class="form-control" />
                  <label class="form-label" for="typeNumber">Berapa Kg Pupuknya?</label>
                </div>
                <button type="submit" class="btn btn-success col-12 mt-2 mb-4" style="border-radius: 10px;">Update Pupuk
                  🧉</button>
              </form>

              <form action="{{ url_for('views.updateBibit') }}" method="post">
                <div class="form-outline col-12">
                  <input type="number" name="bibit" id="typeNumber" class="form-control" />
                  <label class="form-label" for="typeNumber">Berapa Kg Bibitnya?</label>
                </div>
                <button type="submit" class="btn btn-success col-12 mt-2 mb-2" style="border-radius: 10px;">Update Bibit
                  🌱</button>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>

    <footer class="app-footer">
      <div class="container text-center py-3">
        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
        <small class="copyright">Made With <span class="sr-only">love</span><i class="fas fa-heart"
            style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com"
            target="_blank">Chilee IoT Developers

      </div>
    </footer>
    <!--//app-footer-->

  </div>
  <!--//app-wrapper-->
</div>
{% endblock %}

websites/templates/template.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>
		{% block title %} {% endblock %}
	</title>

	<!-- Meta -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
	<meta name="author" content="Xiaoying Riley at 3rd Wave Media">
	<link rel="shortcut icon" href="favicon.ico">
	<!-- Font Awesome -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
	<!-- MDB -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css" rel="stylesheet" />
	<!-- FontAwesome JS-->
	<script defer src="{{ url_for('static', filename = 'plugins/fontawesome/js/all.min.js') }}"></script>

	<!-- App CSS -->
	<link id="theme-style" rel="stylesheet" href="{{ url_for('static', filename = 'css/portal.css') }}">
	<!-- Bootstrap -->
	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.min.css" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

</head>

<body class="app">
	<header class="app-header fixed-top">
		<div class="app-header-inner">
			<div class="container-fluid py-2">
				<div class="app-header-content">

					<div class="row justify-content-between align-items-center">

						<div class="col-auto">
							<a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
								<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img">
									<title>Menu</title>
									<path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2"
										d="M4 7h22M4 15h22M4 23h22"></path>
								</svg>
							</a>
						</div>
						<!--//col-->
						<div class="search-mobile-trigger d-sm-none col">

							<h1 class="app-page-title mt-2">
								<a><span class="badge hours" style="color:green"></span></a> :
								<a><span class="badge min" style="color:green"></span></a> :
								<a><span class="badge sec" style="color:green"></span></a>
							</h1>

						</div>
						<!--//col-->
						<div class="app-search-box col">


							<h1 class="app-page-title mt-2">
								<a><span class="badge hours" style="color:green"></span></a> :
								<a><span class="badge min" style="color:green"></span></a> :
								<a><span class="badge sec" style="color:green"></span></a>
							</h1>

						</div>
						<!--//app-search-box-->

						<div class="app-utilities col-auto">
							<div class="app-utility-item app-user-dropdown dropdown">

							</div>
							<!--//app-user-dropdown-->
						</div>
						<!--//app-utilities-->
					</div>
					<!--//row-->
				</div>
				<!--//app-header-content-->
			</div>
			<!--//container-fluid-->
		</div>
		<!--//app-header-inner-->
		<div id="app-sidepanel" class="app-sidepanel">
			<div id="sidepanel-drop" class="sidepanel-drop"></div>
			<div class="sidepanel-inner d-flex flex-column">
				<a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
				<div class="app-branding">
					<a class="app-logo" href="index.html"><img class="logo-icon me-2"
							src="{{ url_for('static', filename = 'images/app-logo.svg') }}" alt="logo"><span class="logo-text">Chilee
							IoT</span></a>

				</div>
				<!--//app-branding-->

				<nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
					<ul class="app-menu list-unstyled accordion" id="menu-accordion">
						<li class="nav-item">
							<!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
							<a class="nav-link active" href="{{ url_for('views.dashboard') }}">
								<span class="nav-icon">
									<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door" fill="currentColor"
										xmlns="http://www.w3.org/2000/svg">
										<path fill-rule="evenodd"
											d="M7.646 1.146a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5H9.5a.5.5 0 0 1-.5-.5v-4H7v4a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6zM2.5 7.707V14H6v-4a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v4h3.5V7.707L8 2.207l-5.5 5.5z" />
										<path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
									</svg>
								</span>
								<span class="nav-link-text">Overview</span>
							</a>
							<!--//nav-link-->
						</li>

						<li class="nav-item">
							<!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
							<a class="nav-link" href="{{ url_for('views.sistem') }}">
								<span class="nav-icon">
									<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor"
										xmlns="http://www.w3.org/2000/svg">
										<path fill-rule="evenodd"
											d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
										<path fill-rule="evenodd"
											d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z" />
										<circle cx="3.5" cy="5.5" r=".5" />
										<circle cx="3.5" cy="8" r=".5" />
										<circle cx="3.5" cy="10.5" r=".5" />
									</svg>
								</span>
								<span class="nav-link-text">Sistem</span>
							</a>
							<!--//nav-link-->
						</li>
						<li class="nav-item">
							<!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
							<a class="nav-link" href="{{ url_for('views.stok') }}">
								<span class="nav-icon">
									<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor"
										xmlns="http://www.w3.org/2000/svg">
										<path fill-rule="evenodd"
											d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
										<path fill-rule="evenodd"
											d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z" />
										<circle cx="3.5" cy="5.5" r=".5" />
										<circle cx="3.5" cy="8" r=".5" />
										<circle cx="3.5" cy="10.5" r=".5" />
									</svg>
								</span>
								<span class="nav-link-text">Stok</span>
							</a>
							<!--//nav-link-->
						</li>
			</div>
			<!--//sidepanel-inner-->
		</div>
		<!--//app-sidepanel-->
	</header>
	<!--//app-header-->


	{% block body %}


	{% block script %}
	{% endblock %}


	{% endblock %}
	<!-- MDB -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"></script>
	<!-- Javascript -->
	<script src="{{ url_for('static', filename = 'plugins/popper.min.js') }}"></script>
	<script src="{{ url_for('static', filename = 'plugins/bootstrap/js/bootstrap.min.js') }}"></script>


	<script src="{{ url_for('static', filename = 'js/app.js') }}"></script>
	<script src="{{ url_for('static', filename = 'js/jam.js') }}"></script>
</body>




</html>